name: Godot Export

on:
  push:
    branches:
      - main  # Change this if your default branch has a different name
  workflow_dispatch: # Allows manual runs from GitHub UI

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: josephbmanley/godot-action@v2
        with:
          version: "4.4"
          export_templates: true

      - name: Export Game
        run: |
          mkdir -p build
          godot --headless --export-release "Windows Desktop" "build/game.exe"
          godot --headless --export-release "Linux/X11" "build/game.x86_64"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: exported-game
          path: build/
