name: Export Godot Project

on:
  push:
    branches:
      - main  # Trigger on new commits to the main branch

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.4/Godot_v4.4-stable_linux_headless.64.zip
          unzip Godot_v4.4-stable_linux_headless.64.zip
          chmod +x Godot_v4.4-stable_linux_headless.64

      - name: Export for Windows
        run: |
          ./Godot_v4.4-stable_linux_headless.64 --headless --export-release "Windows Desktop" build/windows/game.exe

      - name: Export for Linux
        run: |
          ./Godot_v4.4-stable_linux_headless.64 --headless --export-release "Linux/X11" build/linux/game.x86_64

      - name: Export for macOS
        run: |
          ./Godot_v4.4-stable_linux_headless.64 --headless --export-release "macOS" build/macos/game.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            build/windows/game.exe
            build/linux/game.x86_64
            build/macos/game.zip
