name: Godot Export

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Godot 4.4
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
          unzip Godot_v4.4-stable_linux.x86_64.zip
          chmod +x Godot_v4.4-stable_linux.x86_64
          sudo mv Godot_v4.4-stable_linux.x86_64 /usr/local/bin/godot

      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.4.stable
          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          unzip -o Godot_v4.4-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/
          mv ~/.local/share/godot/export_templates/templates/* ~/.local/share/godot/export_templates/4.4.stable/

      - name: Export for Linux
        run: |
          mkdir -p builds
          godot --headless --export-release "Linux" "builds/double_pendulum.x86_64"

      - name: Export for Windows
        run: |
          mkdir -p builds
          godot --headless --export-release "Windows Desktop" "builds/double_pendulum.exe"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: exported-game
          path: builds/
