name: Godot Export

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch: # Allows manual runs from GitHub UI

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Godot 4.4
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
          unzip Godot_v4.4-stable_linux.x86_64.zip
          chmod +x Godot_v4.4-stable_linux.x86_64
          mv Godot_v4.4-stable_linux.x86_64 /usr/local/bin/godot

      - name: Setup Export Templates
        run: |
          mkdir -p ~/.config/godot
          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          unzip -o Godot_v4.4-stable_export_templates.tpz -d ~/.config/godot

      - name: Export Game
        run: |
          mkdir -p build
          godot --headless --export-release "Windows Desktop" "build/game.exe"
          godot --headless --export-release "Linux/X11" "build/game.x86_64"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: exported-game
          path: build/
